// 🔮 Plugin created by DevAfeez
// ⚙️ Rebranded and enhanced by TruvaGPT
// 📢 Do not remove credits or redistribute without permission.

const axios = require('axios');

async function apiMakerCommand(sock, chatId, message) {
    try {
        const text = message.message?.conversation || message.message?.extendedTextMessage?.text || '';
        const body = text.trim();
        const triggers = ['/api', '/apimaker', '/createapi'];
        const usedTrigger = triggers.find(cmd => body.startsWith(cmd));

        if (!usedTrigger) return;

        const query = body.replace(usedTrigger, '').trim();

        if (!query) {
            const helpMessage = `╔═══ ✦ *🔧 API Maker by TruvaGPT* ✦ ═══╗
🤖 Create and test custom API endpoints easily
╚═══════════════════════════════════╝
│
├◆ 💡 *Usage:* \`/api <METHOD> <ENDPOINT> <RESPONSE_TYPE>\`
│
├◆ 📌 *Examples:*
├◆ /api GET /users json
├◆ /api POST /create-user text
├◆ /api PUT /update-product xml
│
├◆ ⚙️ *Parameters:*
├◆ • METHOD → GET | POST | PUT | DELETE
├◆ • ENDPOINT → Must start with '/'
├◆ • RESPONSE → json | text | xml
│
└─── 💫 *Powered by TruvaGPT*`;

            return await sock.sendMessage(chatId, { text: helpMessage });
        }

        const parts = query.split(/\s+/);
        if (parts.length < 3) {
            return await sock.sendMessage(chatId, { 
                text: `❌ Invalid format!\n\nUse:\n\`/api <METHOD> <ENDPOINT> <RESPONSE_TYPE>\``
            });
        }

        const [method, endpoint, responseType] = parts;
        const validMethods = ['GET', 'POST', 'PUT', 'DELETE'];
        const validResponseTypes = ['json', 'text', 'xml'];

        if (!validMethods.includes(method.toUpperCase())) {
            return await sock.sendMessage(chatId, { 
                text: `🚫 Invalid method!\nUse one of: ${validMethods.join(', ')}`
            });
        }

        if (!endpoint.startsWith('/')) {
            return await sock.sendMessage(chatId, { 
                text: `⚠️ Endpoint must start with '/'\nExample: \`/api GET /users json\``
            });
        }

        if (!validResponseTypes.includes(responseType.toLowerCase())) {
            return await sock.sendMessage(chatId, { 
                text: `❌ Invalid response type!\nChoose: ${validResponseTypes.join(', ')}`
            });
        }

        // React while generating API
        await sock.sendMessage(chatId, { react: { text: '⚙️', key: message.key } });

        const apiStructure = {
            method: method.toUpperCase(),
            endpoint: endpoint,
            responseType: responseType.toLowerCase(),
            createdAt: new Date().toISOString(),
            status: "draft"
        };

        const responseTemplates = {
            json: { status: true, message: "API endpoint created successfully", data: {} },
            text: "API endpoint created successfully ✅",
            xml: `<?xml version="1.0" encoding="UTF-8"?><api><status>true</status><message>API endpoint created successfully</message></api>`
        };

        const responseTemplate = responseTemplates[responseType.toLowerCase()];

        const apiCode = `
// ${apiStructure.method} ${apiStructure.endpoint}
app.${apiStructure.method.toLowerCase()}('${apiStructure.endpoint}', (req, res) => {
    try {
        // Your API logic here
        res.${apiStructure.responseType}(${JSON.stringify(responseTemplate, null, 2)});
    } catch (error) {
        res.status(500).json({ status: false, message: error.message });
    }
});
`;

        const apiDetails = `╔═══ ✦ *🌐 API Endpoint Created!* ✦ ═══╗
🤖 Generated by TruvaGPT
╚═══════════════════════════════════╝
│
├◆ 📍 Method: *${apiStructure.method}*
├◆ 🔗 Endpoint: *${apiStructure.endpoint}*
├◆ 💾 Response Type: *${apiStructure.responseType}*
├◆ ⏰ Created: *${new Date(apiStructure.createdAt).toLocaleString()}*
│
├◆ 🧩 *Implementation Example:*
\`\`\`javascript
${apiCode}
\`\`\`
│
├◆ 📦 *Sample Response:*
\`\`\`${apiStructure.responseType}
${JSON.stringify(responseTemplate, null, 2)}
\`\`\`
│
└─── ✨ *TruvaGPT API Maker Complete!*`;

        await sock.sendMessage(chatId, {
            text: apiDetails,
            contextInfo: {
                forwardingScore: 1,
                isForwarded: false,
                forwardedNewsletterMessageInfo: {
                    newsletterJid: '120363401657714060@newsletter',
                    newsletterName: 'TruvaGPT',
                    serverMessageId: -1
                }
            }
        });

        await sock.sendMessage(chatId, { react: { text: '✅', key: message.key } });

    } catch (error) {
        console.error('API Maker Error:', error);
        await sock.sendMessage(chatId, {
            text: `❌ *API Creation Failed!*\n\nError: ${error.message}`
        });
    }
}

module.exports = apiMakerCommand;